<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>

    <ItemGroup>
        <Antlr4 Include="BishLexer.g4">
            <Generator>MSBuild:Compile</Generator>
            <CustomToolNamespace>BishCompiler</CustomToolNamespace>
            <TargetLanguage>CSharp</TargetLanguage>
        </Antlr4>
        <Antlr4 Include="BishParser.g4">
            <Generator>MSBuild:Compile</Generator>
            <CustomToolNamespace>BishCompiler</CustomToolNamespace>
            <TargetLanguage>CSharp</TargetLanguage>
            <Antlr4GenVisitor>True</Antlr4GenVisitor>
            <Antlr4GenListener>False</Antlr4GenListener>
        </Antlr4>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Antlr4.Runtime.Standard" Version="4.13.1"/>
        <PackageReference Include="Antlr4BuildTasks" Version="12.14.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\BishRuntimeGenerators\BishRuntimeGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
        <ProjectReference Include="..\BishRuntime\BishRuntime.csproj">
            <Private>false</Private>
            <PrivateAssets>all</PrivateAssets>
            <ExcludeAssets>runtime</ExcludeAssets>
        </ProjectReference>
    </ItemGroup>

    <Target Name="PostBuild" AfterTargets="PostBuildEvent">
        <ItemGroup>
            <PluginFiles Include="$(OutputPath)$(AssemblyName).dll;$(OutputPath)Antlr4.Runtime.Standard.dll" />
        </ItemGroup>

        <PropertyGroup>
            <PluginsDir>$(SolutionDir)publish/</PluginsDir>
        </PropertyGroup>

        <Copy SourceFiles="@(PluginFiles)" DestinationFolder="$(PluginsDir)" SkipUnchangedFiles="true" />
    </Target>

    <PropertyGroup>
        <Antlr4ToolJarPath>$(ProjectDir)tools/antlr.jar</Antlr4ToolJarPath>
    </PropertyGroup>
</Project>
