namespace BishRuntimeGenerators;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Linq;
using System.Text;

[Generator]
public class BuiltinsGenerator : IIncrementalGenerator
{
    private static string? GetNamespace(SyntaxNode node)
    {
        var namespaceDeclaration = node.Ancestors()
            .OfType<BaseNamespaceDeclarationSyntax>()
            .FirstOrDefault();

        return namespaceDeclaration?.Name.ToString();
    }

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var builtins = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (node, _) => IsTargetMethod(node),
                transform: (ctx, _) => GetBuiltinStuff(ctx))
            .Where(details => details is not null);

        context.RegisterSourceOutput(builtins.Collect(), (spc, methods) =>
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine();
            foreach (var ns in methods.Select(m => m!.Namespace).Append("BishRuntime").OfType<string>().Distinct())
                sb.AppendLine($"using {ns};");
            sb.AppendLine();
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("internal static class BuiltinsRegistry");
            sb.AppendLine("{");
            sb.AppendLine("    public static void Register()");
            sb.AppendLine("    {");
            foreach (var method in methods.OfType<IBuiltinStuff>())
            foreach (var line in method.Code.Split('\n'))
                if (line.Trim() != "")
                    sb.AppendLine("        " + line);
            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource("BuiltinsRegistry.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        });
    }

    private static bool IsTargetMethod(SyntaxNode node) =>
        node is MethodDeclarationSyntax { AttributeLists.Count: > 0 };

    private static BuiltinFunction? GetBuiltinFunction(GeneratorSyntaxContext context)
    {
        var method = (MethodDeclarationSyntax)context.Node;

        var attrs = method.AttributeLists.SelectMany(al => al.Attributes).ToList();
        var attr = attrs.FirstOrDefault(a => a.Name.ToString() == "Builtin");

        if (attr is null) return null;

        var attrArgs = GetAttributeArguments(attr, ["prefix", "tag"]);

        var classDecl = method.Parent as ClassDeclarationSyntax;
        var className = classDecl?.Identifier.Text ?? "Global";

        var args = method.ParameterList.Parameters.Select(param =>
        {
            var name = param.Identifier.Text;
            var type = param.Type?.ToString().TrimEnd("?").ToString() ?? "dynamic";
            var attrList = param.AttributeLists
                .SelectMany(al => al.Attributes)
                .Select(a => a.ToString()).ToList();
            var isDefault = attrList.Contains("DefaultNull");
            var isRest = attrList.Contains("Rest");
            return new BuiltinFunctionArg(type, name, isDefault, isRest);
        }).ToArray();

        var returnType = method.ReturnType.ToString();

        var passCaller = attrs.Any(a => a.Name.ToString() == "PassCaller");

        var details = new BuiltinFunction(className, attrArgs[0], method.Identifier.Text, args, attrArgs[1],
            returnType == "void", returnType.EndsWith("?"), passCaller, GetNamespace(method));

        return details;
    }

    private static string?[] GetAttributeArguments(AttributeSyntax attr, string[] argNames)
    {
        var result = new string?[argNames.Length];
        if (attr.ArgumentList == null) return result;
        var arguments = attr.ArgumentList.Arguments;
        for (var i = 0; i < arguments.Count; i++)
        {
            var arg = arguments[i];
            if (arg.NameEquals != null)
            {
                var name = arg.NameEquals.Name.Identifier.Text;
                var index = Array.IndexOf(argNames, name);
                if (index != -1) result[index] = ExtractValue(arg.Expression);
            }
            else if (i < argNames.Length) result[i] = ExtractValue(arg.Expression);
        }

        return result;
    }

    private static string? ExtractValue(ExpressionSyntax expression)
    {
        var raw = expression.ToString().Trim();
        return raw == "null" ? null : raw.Trim('"');
    }

    private static BuiltinIterator? GetBuiltinIter(GeneratorSyntaxContext context)
    {
        var method = (MethodDeclarationSyntax)context.Node;

        var attr = method.AttributeLists.SelectMany(al => al.Attributes)
            .FirstOrDefault(a => a.Name.ToString() == "Iter");

        if (attr is null) return null;

        var classDecl = method.Parent as ClassDeclarationSyntax;
        var className = classDecl?.Identifier.Text ?? "Global";

        return new BuiltinIterator(className, GetNamespace(method));
    }

    private static BuiltinAsync? GetBuiltinAsync(GeneratorSyntaxContext context)
    {
        var method = (MethodDeclarationSyntax)context.Node;

        var attr = method.AttributeLists.SelectMany(al => al.Attributes)
            .FirstOrDefault(a => a.Name.ToString() == "Async");

        if (attr is null) return null;

        var classDecl = method.Parent as ClassDeclarationSyntax;
        var className = classDecl?.Identifier.Text ?? "Global";

        return new BuiltinAsync(className, GetNamespace(method));
    }

    private static IBuiltinStuff? GetBuiltinStuff(GeneratorSyntaxContext context) =>
        GetBuiltinFunction(context) ?? GetBuiltinIter(context) ?? (IBuiltinStuff?)GetBuiltinAsync(context);
}

public record BuiltinIterator(string Type, string? Namespace) : IBuiltinStuff
{
    public string Code =>
        $"BishBuiltinIteratorBinder.Bind({Type}.StaticType, " +
        $"obj => obj.As<{Type}>(\"self\").Next(), {(Type == "BishIterator").ToString().ToLower()});";
}

public record BuiltinAsync(string Type, string? Namespace) : IBuiltinStuff
{
    public string Code =>
        $"BishBuiltinTaskBinder.Bind({Type}.StaticType, (obj, ctx) => obj.As<{Type}>(\"self\").Poll(ctx));";
}