namespace BishRuntimeGenerators;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Linq;
using System.Text;

[Generator]
public class BuiltinFunctionGenerator : IIncrementalGenerator
{
    private static string? GetNamespace(SyntaxNode node)
    {
        var namespaceDeclaration = node.Ancestors()
            .OfType<BaseNamespaceDeclarationSyntax>()
            .FirstOrDefault();

        return namespaceDeclaration?.Name.ToString();
    }

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var methodDetails = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (node, _) => IsTargetMethod(node),
                transform: (ctx, _) => GetMethodDetails(ctx))
            .Where(details => details != null);

        context.RegisterSourceOutput(methodDetails.Collect(), (spc, methods) =>
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine();
            foreach (var ns in methods.Select(m => m!.Namespace).Append("BishRuntime").OfType<string>().Distinct())
                sb.AppendLine($"using {ns};");
            sb.AppendLine();
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("public static class BuiltinFunctionRegistry");
            sb.AppendLine("{");
            sb.AppendLine("    public static void Registry()");
            sb.AppendLine("    {");
            foreach (var method in methods.OfType<BuiltinFunction>())
                sb.AppendLine(method.ToString());
            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource("BuiltinFunctionRegistry.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        });
    }

    private static bool IsTargetMethod(SyntaxNode node) =>
        node is MethodDeclarationSyntax { AttributeLists.Count: > 0 };

    private static BuiltinFunction? GetMethodDetails(GeneratorSyntaxContext context)
    {
        var method = (MethodDeclarationSyntax)context.Node;
        const string targetAttr = "Builtin";

        var attr = method.AttributeLists.SelectMany(al => al.Attributes)
            .FirstOrDefault(a => a.Name.ToString() == targetAttr || a.Name.ToString() == $"{targetAttr}Attribute");

        if (attr is null) return null;

        var attrArgs = GetAttributeArguments(attr, ["prefix", "tag"]);

        var classDecl = method.Parent as ClassDeclarationSyntax;
        var className = classDecl?.Identifier.Text ?? "Global";

        var args = method.ParameterList.Parameters.Select(param =>
        {
            var name = param.Identifier.Text;
            var type = param.Type?.ToString().TrimEnd("?").ToString() ?? "dynamic";
            var attrs = param.AttributeLists
                .SelectMany(al => al.Attributes)
                .Select(a => a.ToString()).ToList();
            var isDefault = attrs.Contains("DefaultNull");
            var isRest = attrs.Contains("Rest");
            return new BuiltinFunctionArg(type, name, isDefault, isRest);
        }).ToArray();

        var returnType = method.ReturnType.ToString();

        var details = new BuiltinFunction(className, attrArgs[0], method.Identifier.Text, args, attrArgs[1],
            returnType == "void", returnType.EndsWith("?"), GetNamespace(method));

        return details;
    }

    private static string?[] GetAttributeArguments(AttributeSyntax attr, string[] argNames)
    {
        var result = new string?[argNames.Length];
        if (attr.ArgumentList == null) return result;
        var arguments = attr.ArgumentList.Arguments;
        for (var i = 0; i < arguments.Count; i++)
        {
            var arg = arguments[i];
            if (arg.NameEquals != null)
            {
                var name = arg.NameEquals.Name.Identifier.Text;
                var index = Array.IndexOf(argNames, name);
                if (index != -1) result[index] = ExtractValue(arg.Expression);
            }
            else if (i < argNames.Length) result[i] = ExtractValue(arg.Expression);
        }

        return result;
    }

    private static string? ExtractValue(ExpressionSyntax expression)
    {
        var raw = expression.ToString().Trim();
        return raw == "null" ? null : raw.Trim('"');
    }
}