using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Text;

namespace BishRuntimeGenerators;

#pragma warning disable RS2008

[Generator]
public class BytecodeParserGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor Descriptor = new(
        id: "BTGEN001",
        title: "Bytecode Parser Generator Error",
        messageFormat: "{0}",
        category: "BytecodeParserGeneratorUsage",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true
    );

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<BytecodeInfo> infos = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is RecordDeclarationSyntax,
                transform: static (ctx, _) => GetRecordInfo(ctx)
            )
            .Where(static info => info != null)!;

        context.RegisterSourceOutput(infos.Collect(), (spc, bytecodes) =>
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using System.Text.RegularExpressions;");
            sb.AppendLine("using BishRuntime;");
            sb.AppendLine();
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("public static class BytecodeParserRegistry");
            sb.AppendLine("{");
            sb.AppendLine("    public static void Register()");
            sb.AppendLine("    {");
            foreach (var bytecode in bytecodes.OfType<BytecodeInfo>().OrderBy(info => info.Name))
            {
                try
                {
                    foreach (var line in bytecode.Code.Split('\n'))
                        if (line.Trim() != "")
                            sb.AppendLine("        " + line);
                }
                catch (ArgumentException e)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(Descriptor, null, e.Message));
                }
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource("BytecodeParserRegistry.g.cs", sb.ToString());
        });
    }

    private static BytecodeInfo? GetRecordInfo(GeneratorSyntaxContext context)
    {
        var recordDecl = (RecordDeclarationSyntax)context.Node;

        if (!recordDecl.AttributeLists.Any(attrList =>
                attrList.Attributes.Any(attr => attr.Name.ToString() == "Bytecode")))
            return null;

        var paramList = recordDecl.ParameterList;
        var recordName = recordDecl.Identifier.Text;

        return new BytecodeInfo(recordName, paramList?.Parameters.Select(param =>
            RecordArg.From(param.ToString().Trim())).ToImmutableArray() ?? []);
    }
}

public record RecordArg(string Type, string Name, string? Default)
{
    public static RecordArg From(string full)
    {
        var spiltDefault = full.Split('=');
        var defaultValue = spiltDefault.Length > 1 ? spiltDefault[1] : null;
        var parts = spiltDefault[0].Split(' ');
        return new RecordArg(parts[0].Trim(), parts[1].Trim(), defaultValue?.Trim());
    }

    private static string Escape(string var) => $"'\"' + Regex.Escape({var}) + '\"'";

    private static string EscapeTag(string var) => $"{var}.S is null ? {var}.B.ToString() : ({Escape($"{var}.S")})";

    public string Format => Type switch
    {
        "int" or "double" => $"bytecode.{Name}.ToString()",
        "bool" => $"bytecode.{Name}.ToString().ToLower()",
        "string" => Escape($"bytecode.{Name}"),
        "Tag" or "Tag?" => $"bytecode.{Name} is null ? \"null\" : {EscapeTag($"bytecode.{Name}")}",
        "IList<string>" => $"'[' + string.Join(\", \", bytecode.{Name}.Select(s => {Escape("s")})) + ']'",
        _ => throw new ArgumentException($"Invalid bytecode argument type: {Type}")
    };

    public string AsType => Type switch
    {
        "int" or "double" or "bool" or "string" or "Tag" => Type.Upper(),
        "Tag?" => "Tag",
        "IList<string>" => "Strings",
        _ => throw new ArgumentException($"Invalid bytecode argument type: {Type}")
    };
}

public record BytecodeInfo(string Name, ImmutableArray<RecordArg> Args)
{
    public string FullName => $"BishRuntime.{Name}";

    public string Code =>
        $$"""
          BishBytecodeParser.Parsers.Add(new BytecodeParser(
              typeof({{FullName}}),
              b =>
              {
                  var bytecode = ({{FullName}})b;
                  return string.Join(" ", ["{{Name}}", {{string.Join(", ", Args.Select(arg => arg.Format))}}]);
              },
              (b, writer) =>
              {
                  var bytecode = ({{FullName}})b;
                  {{string.Join(";\n        ", Args.Select(arg => $"writer.Add{arg.AsType}(bytecode.{arg.Name})"))}};
              },
              reader =>
              {
                  {{string.Join(";\n        ", Args.Select(arg => $"var arg{arg.Name} = reader.Get{arg.AsType}()"))}};
                  return new {{FullName}}({{string.Join(", ", Args.Select(arg => "arg" + arg.Name + (arg.Type == "Tag" ? "!" : "")))}});
              },
              (b, obj) =>
              {
                  var bytecode = ({{FullName}})b;
                  {{string.Join(";\n        ", Args.Select(arg => $"obj.Add{arg.AsType}(\"{arg.Name.Lower()}\", bytecode.{arg.Name})"))}};
              },
              obj =>
              {
                  {{string.Join(";\n        ", Args.Select(arg => $"var arg{arg.Name} = obj.Get{arg.AsType}(\"{arg.Name.Lower()}\"{(arg.Default is null or "null" ? "" : ", " + arg.Default)})"))}};
                  return new {{FullName}}({{string.Join(", ", Args.Select(arg => "arg" + arg.Name + (arg.Type == "Tag" ? "!" : "")))}});
              }
              ));
          """;
}