name: Publish

on: [ push, pull_request ]

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: windows-latest
            runtime: win-x64
            asset_suffix: .exe
          - os: ubuntu-latest
            runtime: linux-x64
            asset_suffix: ''
          - os: macos-latest
            runtime: osx-x64
            asset_suffix: ''

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set GH_TOKEN environment variable (Linux/Mac)
        if: ${{ matrix.os != 'windows-latest' }}
        run: echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV
        shell: bash

      - name: Set GH_TOKEN environment variable (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $env:GITHUB_ENV
        shell: pwsh
        
      - name: Download ANTLR
        shell: bash
        run: |
          mkdir ./BishCompiler/tools
          curl -L https://www.antlr.org/download/antlr-4.13.2-complete.jar -o ./BishCompiler/tools/antlr.jar

      - name: Publish main project
        run: |
          dotnet publish ./Bish/Bish.csproj -c Release -r ${{ matrix.runtime }} --self-contained true /p:PublishSingleFile=true -o ./publish

      - name: Publish VSCode extension project
        shell: bash
        run: |
          cd ./BishLSP/bish-vsc
          npm install
          npx @vscode/vsce package -o Bish-vsc.vsix
          cp Bish-vsc.vsix ../../publish

      - name: Upload main artifact for ${{ matrix.os }}
        uses: actions/upload-artifact@v4
        with:
          name: Bish-${{ matrix.os }}${{ matrix.asset_suffix }}
          path: publish/Bish${{ matrix.asset_suffix }}

      - name: Upload VSCode extension artifact for ${{ matrix.os }}
        uses: actions/upload-artifact@v4
        with:
          name: Bish-vsc-${{ matrix.os }}.vsix
          path: publish/Bish-vsc.vsix